/**
 * Harness Core Types
 *
 * Central type definitions for the CodeContext harness framework.
 * Defines Run identity, lifecycle, status, checkpoints, and manifest contracts.
 *
 * PRD §34: Harness — unified business closed-loop execution framework.
 */

// ── Run Identity ──────────────────────────────────────────────────────────────

/** Unique run identifier (e.g. "run_20260615_abc123_001"). */
export type RunId = string & { readonly __brand: "RunId" };

/** Monotonic checkpoint counter within a single run. */
export type CheckpointSeq = number;

// ── Run Status ────────────────────────────────────────────────────────────────

export type RunStatus = "created" | "running" | "passed" | "failed" | "aborted";

export const RUN_STATUS_TRANSITIONS: Record<RunStatus, readonly RunStatus[]> = {
  created: ["running", "aborted"],
  running: ["passed", "failed", "aborted"],
  passed: [],
  failed: [],
  aborted: [],
} as const;

// ── Checkpoint ────────────────────────────────────────────────────────────────

/** A single checkpoint entry logged during a run. */
export interface Checkpoint {
  /** Monotonic sequence number within the run. */
  seq: CheckpointSeq;
  /** ISO 8601 timestamp. */
  timestamp: string;
  /** Human-readable label (e.g. "compress:code", "recall:fts_search"). */
  label: string;
  /** Outcome of this step. */
  outcome: "pass" | "fail" | "warn" | "skip";
  /** Optional diagnostic message. */
  message?: string;
  /** Optional structured metadata (e.g. token counts, timing). */
  metadata?: Record<string, unknown>;
}

// ── Run Record ────────────────────────────────────────────────────────────────

/** Persisted run execution record. */
export interface RunRecord {
  runId: RunId;
  /** The manifest that defined this run. */
  manifestName: string;
  scopeId: string;
  status: RunStatus;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  /** ISO 8601 completion timestamp (set when terminal). */
  completedAt?: string;
  /** Ordered list of checkpoints logged during the run. */
  checkpoints: Checkpoint[];
  /** Run-level receipt ID (references sub-receipts). */
  runReceiptId?: string;
  /** Sub-receipt IDs generated by individual operations. */
  subReceiptIds: string[];
  /** Free-form tags for categorization. */
  tags: string[];
  /** Arbitrary metadata. */
  metadata: Record<string, unknown>;
}

// ── Manifest ──────────────────────────────────────────────────────────────────

/** Declares a business-capability closed loop to execute. */
export interface Manifest {
  /** Unique manifest name (e.g. "compressionFlow"). */
  name: string;
  /** Human-readable description. */
  description: string;
  /** Which closed loop this manifest exercises. */
  loopType: LoopType;
  /** Ordered step declarations — what the loop should exercise, not how. */
  steps: ManifestStep[];
  /** Optional tags for filtering/discovery. */
  tags?: string[];
}

export type LoopType =
  | "compression"
  | "originals"
  | "memory"
  | "profile"
  | "fullContext"
  | "mcpToolsSmoke"
  | "cliSmoke";

/** A single step within a manifest. Declares intent, not implementation. */
export interface ManifestStep {
  /** Step identifier within the manifest (e.g. "detect_content_type"). */
  name: string;
  /** Human-readable description of what this step verifies. */
  description: string;
  /** Expected outcome kind. */
  expect: "success" | "failure" | "warning" | "any";
  /** Optional input fixture reference. */
  fixture?: string;
}

// ── Run Context ───────────────────────────────────────────────────────────────

/**
 * Services and state available to a flow during execution.
 *
 * The `adapter` field is optional — stub flows work without it;
 * production flows receive a fully wired CodeContextAdapter.
 */
export interface RunContext {
  runId: RunId;
  manifest: Manifest;
  scopeId: string;
  /** Unified adapter to CodeContext services (compression, memory, profile, etc.). */
  adapter?: import("../adapters/codeContextAdapter.js").CodeContextAdapter;
}
